acmeRoot:
  ip: 192.168.49.2
  port: 9090
acmeSubdomain:
- ip: 192.168.49.2
  name: www
  port: 9090
- ip: 192.168.49.2
  name: home
  port: 9090
- ip: 192.168.49.2
  name: git
  port: 9090
- ip: 192.168.49.2
  name: player
  port: 9090
- ip: 192.168.49.2
  name: browser
  port: 9090
dnsIp: 91.149.218.39
dnsName: spongo.ru
haproxyRoot:
  ip: 192.168.49.2
  port: 8888
haproxySubdomain:
- ip: 192.168.49.2
  name: www
  port: 8888
  proxy: false
- ip: 127.0.0.1
  name: vpn
  port: 9443
  proxy: false
- ip: 127.0.0.1
  name: nebula
  port: 4242
  proxy: false
- ip: 127.0.0.1
  name: shadowsocks
  port: 9389
  proxy: false
- ip: 192.168.49.2
  name: router
  port: 443
  proxy: false
- ip: 192.168.49.2
  name: player
  port: 8000
  proxy: false
- ip: 192.168.49.2
  name: home
  port: 8899
  proxy: false
- ip: 192.168.49.2
  name: git
  port: 8797
  proxy: false
- ip: 192.168.49.2
  name: browser
  port: 9797
  proxy: false
straightProxy:
- name: test
  extPort: 4090
  intPort: 2222
  intIp: 1.1.0.1
# - name: sshr3g
#   extPort: 4091
#   intPort: 22
#   intIp: 192.168.49.5