name: openwrt-bpi-r3-mini-nginx
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/openwrt/bpi-r3-mini/**
  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 192.168.49.2
          username: ${{ secrets.R3MUSERNAME }}
          password: ${{ secrets.R3MPASSWORD }}
          port: 4090
          script_path: iac/openwrt/bpi-r3-mini/scripts/nginx-allconf.sh